### ISSUE TITLE
Error in task/masters.yml

### ISSUE THREAD

**Issue by prakhar1985** [samdoran/ansible-role-pgsql-replication#8]
TASK [samdoran.pgsql_replication : Add trust in pg_hba.conf] ************************************************************
fatal: [support2]: FAILED! => {"msg": "Invalid data passed to 'loop', it requires a list, got this instead: 192.168.1.148. Hint: If you passed a list/dict of just one element, try adding wantlist=True to your lookup invocation or use q/query instead of lookup."}.

I could fix the error by changing the code to 

```
- name: Add trust in pg_hba.conf
  lineinfile:
    state: present
    dest: "{{ pgsqlrep_data_path }}/pg_hba.conf"
    regexp: 'host.*replication.*{{ item }}/32.*trust'
    line: 'host    replication    {{ pgsqlrep_user }}  {{ item }}/32 trust'
  loop:
    - "{{ pgsqlrep_replica_address | list | join }}"
  notify: restart postgresql

```
